### ISSUE TITLE
while exporting the experiment we are facing issue 

### ISSUE THREAD

**Issue by surendraThot** [amesar/mlflow-export-import#1]
while we bring to export the experiment from one Databricks Workspace we are getting the fallowing error 

(mlflow-export-import-env) (base) semac5002:mlflow_export_import tempsutho$ python3 -u -m mlflow_export_import.experiment.export_experiments \
>   --experiments 3903592783888150  --output-dir /Users/tempsutho/Documents/MLFlowexportImport/experiments
MLflow Version: 1.12.0
MLflow Tracking URI: databricks
Options:
  experiments: 3903592783888150
  output_dir: /Users/tempsutho/Documents/MLFlowexportImport/experiments
  export_metadata_tags: False
  notebook_formats: SOURCE
Experiments:
  3903592783888150
Filesystem: LocalFileSystem
WARNING: cannot import name 'databricks_cli_utils' from 'common' (/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/common/__init__.py)
Traceback (most recent call last):
  File "/Users/tempsutho/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tempsutho/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/experiment/export_experiments.py", line 108, in <module>
    main()
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow-export-import-env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow-export-import-env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow-export-import-env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow-export-import-env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/experiment/export_experiments.py", line 88, in main
    exporter = ExperimentExporter(client, export_metadata_tags, utils.string_to_list(notebook_formats))
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/experiment/export_experiments.py", line 24, in __init__
    self.run_exporter = RunExporter(self.client, export_metadata_tags, notebook_formats, self.fs)
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/run/export_run.py", line 23, in __init__
    self.dbx_client = DatabricksHttpClient()
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/common/http_client.py", line 56, in __init__
    super().__init__("api/2.0", host, token)
  File "/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/common/http_client.py", line 14, in __init__
    raise MlflowToolsException("MLflow host or token is not configured correctly")
mlflow_export_import.common.MlflowToolsException: MLflow host or token is not configured correctly

we have provide the 

export MLFLOW_TRACKING_URI=databricks
export DATABRICKS_HOST=https://northeurope.azuredatabricks.net
export DATABRICKS_TOKEN= my token here 

python3 -u -m mlflow_export_import.experiment.export_experiments \
  --experiments 3903592783888150  --output-dir /Users/tempsutho/Documents/MLFlowexportImport/experiments

**Comment by murilommen** [comment]
Hi @surendraThot ! does your "Host" have some unique identification? For instance, mine is `https://adb-<lots-of-numbers>.azuredatabricks.net/`

**Comment by seanblumenfeld** [comment]
Hello @surendraThot - late comment but I think this line in your error is the problem
```
WARNING: cannot import name 'databricks_cli_utils' from 'common' (/Users/tempsutho/Documents/MLFlowexportImport/mlflow-export-import/mlflow_export_import/common/init.py)
```
