### ISSUE TITLE
Exporting model results in InvalidSchema("No connection adapters were found for {!r}".format(url))

### ISSUE THREAD

**Issue by uvnikgupta** [amesar/mlflow-export-import#11]
I have a MLFlow deployment running in kubernetes that uses Minio as the artifact store and postgres as the backed store. I have registered my runs as <code>regres</code> and promoted them to <code>Staging</code>. When I try to export this model using <code>python -u -m mlflow_export_import.model.export_model --model regres --output-dir out</code> I get the following error:
```
Databricks REST client: postgresql+psycopg2://postgres:password@localhost:32345\api/2.0
Filesystem: LocalFileSystem
Traceback (most recent call last):
  File "C:\Miniconda3\envs\mlflow-export-import\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Miniconda3\envs\mlflow-export-import\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\export_import\mlflow_export_import\model\export_model.py", line 59, in <module>
    main()
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "D:\export_import\mlflow_export_import\model\export_model.py", line 56, in main
    exporter.export_model(output_dir, model)
  File "D:\export_import\mlflow_export_import\model\export_model.py", line 22, in export_model
    model = self.client2.get(f"registered-models/get?name={model_name}")
  File "D:\export_import\mlflow_export_import\common\http_client.py", line 28, in get
    return json.loads(self._get(resource).text)
  File "D:\export_import\mlflow_export_import\common\http_client.py", line 23, in _get
    rsp = requests.get(uri, headers=self._mk_headers())
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\requests\sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\requests\sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'postgresql+psycopg2://postgres:password@localhost:32345\\api/2.0/preview/mlflow/registered-models/get?name=regres'
```
I have the following environment variables:
```
MLFLOW_ARTIFACT_STORE=s3://mlruns
MLFLOW_S3_ENDPOINT_URL=http://localhost:30009
MLFLOW_TRACKING_URI=postgresql+psycopg2://postgres:password@localhost:32345
```

**Comment by amesar** [comment]
This is not an mlflow-export-import issue. You have a bad value for MLFLOW_TRACKING_URI. It should point to the MLflow tracking server such as ttp://localhost:5000.

See: https://mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers

**Comment by uvnikgupta** [comment]
Thanks @amesar for pointing out the error.
I have now modified the env variable to <code>MLFLOW_TRACKING_URI=http://localhost:30005</code>
After making this change I tried to curl this endpoint using <code>curl %MLFLOW_TRACKING_URI% </code> and was able to get the response successfully:
`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><link rel="shortcut icon" href="static-files/favicon.ico"><meta name="theme-color" content="#000000"><link rel="manifest" href="static-files/manifest.json"><link rel="stylesheet" href="static-files/bootstrap/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"><link rel="stylesheet" href="static-files/fontawesome/css/fontawesome-all.min.css"><title>MLflow</title><link href="static-files/static/css/2.04a02747.chunk.css" rel="stylesheet"><link href="static-files/static/css/main.3eada216.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><div id="modal"></div><script>!function(l){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],i=0,f=[];i<n.length;i++)t=n[i],c[t]&&f.push(c[t][0]),c[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(l[r]=o[r]);for(s&&s(e);f.length;)f.shift()();return p.push.apply(p,u||[]),a()}function a(){for(var e,r=0;r<p.length;r++){for(var t=p[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==c[u]&&(n=!1)}n&&(p.splice(r--,1),e=i(i.s=t[0]))}return e}var t={},c={1:0},p=[];function i(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return l[e].call(r.exports,r,r.exports,i),r.l=!0,r.exports}i.m=l,i.c=t,i.d=function(e,r,t){i.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},i.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},i.t=function(r,e){if(1&e&&(r=i(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(i.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)i.d(t,n,function(e){return r[e]}.bind(null,n));return t},i.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(r,"a",r),r},i.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},i.p="static-files/";var r=window.webpackJsonp=window.webpackJsonp||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;a()}([])</script><script src="static-files/static/js/2.9f95c1f1.chunk.js"></script><script src="static-files/static/js/main.d5355c77.chunk.js"></script></body></html>`

But when I try to use the export_import utility to export the registered model, I still get the following error:
```
MLflow Version: 1.19.0
MLflow Tracking URI: http://localhost:30005
Options:
  model: regres
  output_dir: out
Databricks REST client: http://localhost:30005\api/2.0
Filesystem: LocalFileSystem
Traceback (most recent call last):
  File "C:\Miniconda3\envs\mlflow-export-import\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\export_import\mlflow_export_import\model\export_model.py", line 59, in <module>
    main()
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniconda3\envs\mlflow-export-import\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "D:\export_import\mlflow_export_import\model\export_model.py", line 56, in main
    exporter.export_model(output_dir, model)
  File "D:\export_import\mlflow_export_import\model\export_model.py", line 22, in export_model
    model = self.client2.get(f"registered-models/get?name={model_name}")
  File "D:\export_import\mlflow_export_import\common\http_client.py", line 28, in get
    return json.loads(self._get(resource).text)
  File "D:\export_import\mlflow_export_import\common\http_client.py", line 24, in _get
    self._check_response(rsp, uri)
  File "D:\export_import\mlflow_export_import\common\http_client.py", line 49, in _check_response
    raise MlflowToolsException(f"HTTP status code: {rsp.status_code}. Reason: {rsp.reason} URL: {uri}")
mlflow_export_import.common.MlflowToolsException: HTTP status code: 404. Reason: NOT FOUND URL: http://localhost:30005\api/2.0/preview/mlflow/registered-models/get?name=regres
```

**Comment by amesar** [comment]
Looks like you have a bad URI - note the backslash: http://localhost:30005\apii
