### ISSUE TITLE
migrate with missing artifacts

### ISSUE THREAD

**Issue by geobao** [amesar/mlflow-export-import#39]
I no longer have the artifacts of a run. Thus I cannot migrate it because it does not find them.
I am trying to figure out a workaround. Do you thing it is worth to add an optional flag to ignore the artifacts?

```root@f0d86eff65f6:/workdir# python -u -m mlflow_export_import.experiment.copy_experiment \
>   --src-experiment 1 \
>   --dst-experiment-name EXP-demo \
>   --src-uri file:///workdir/mlruns \
>   --dst-uri MYURI
```

```MLflow Version: 1.20.2
MLflow Tracking URI: file:///workdir/mlruns
Options:
  export_metadata_tags: False
  use_src_user_id: False
  dst_experiment_name: EXP-demo
  src_experiment: 1
  dst_uri: MYURI
  src_uri: file:///workdir/mlruns
src_client: file:///workdir/mlruns
dst_client: MYURI

src_experiment_name: EXP-demo
src_experiment_id: 1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/mlflow_export_import/experiment/copy_experiment.py", line 77, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mlflow_export_import/experiment/copy_experiment.py", line 74, in main
    copier.copy_experiment(src_experiment, dst_experiment_name)
  File "/usr/local/lib/python3.6/dist-packages/mlflow_export_import/experiment/copy_experiment.py", line 27, in copy_experiment
    dst_run_id, src_parent_run_id = self.run_copier._copy_run(run.info.run_id, dst_exp.experiment_id)
  File "/usr/local/lib/python3.6/dist-packages/mlflow_export_import/run/copy_run.py", line 32, in _copy_run
    local_path = self.src_client.download_artifacts(src_run_id,"")
  File "/usr/local/lib/python3.6/dist-packages/mlflow/tracking/client.py", line 1389, in download_artifacts
    return self._tracking_client.download_artifacts(run_id, path, dst_path)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/tracking/_tracking_service/client.py", line 361, in download_artifacts
    return self._get_artifact_repo(run_id).download_artifacts(path, dst_path)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/store/artifact/local_artifact_repo.py", line 79, in download_artifacts
    raise IOError("No such file or directory: '{}'".format(local_artifact_path))
OSError: No such file or directory: '/home/username/Downloads/demo/mlruns/1/ec329fa00a5e45ca9c234a729fdd7bbf/artifacts/.'`
```

**Comment by amesar** [comment]
Does it make sense to export a run whose artifacts have been deleted. Seems like a corrupt state. If you don't have a model artifact, how will you score?

**Comment by KuenstlicheIntelligenz** [comment]
Hey,

Im working with gcs artifact store.

I also think exporting the artifacts should be made optional. 
We have large amount of runs with different hyperparams which all have automatically uploaded artifacts which we wont need. The information what hyperparamset worked and what not is still important.
Our mlflow gcs storage is so big, im not sure i could download it on any other "normal" machine. Downloading it all would also mean huge datatransfers with a "middleman" instead of directly copy it from one bucket to another.

@geobao a quckfix would be just to comment out the downloading of the artifacts.

The remaining problem is that the importing is changing the experiment id, so mlflow wont find the correct artifacts. I try to find a workaround, maybe ill just rename the artiact paths...

**Comment by amesar** [comment]
Experiment ID and run ID are auto-generated UUIDs so there is no way to preserve them on an import. Using "models:" URI would allow your scoring code to remain unchanged.

If you don't download the model artifact, how would you score your model?

**Comment by amesar** [comment]
> The remaining problem is that the importing is changing the experiment id and also the run_id?.

See last comment in: https://github.com/amesar/mlflow-export-import/issues/42
